### ISSUE TITLE
Launch error

### ISSUE THREAD

**Issue by Bwolfs2** [swift-kim/flutter-tizen-1#1]
Can u help me with this error?
![image](https://user-images.githubusercontent.com/4654514/100175894-05b70600-2eae-11eb-8534-37738c195485.png)

**Comment by swift-kim** [comment]
As stated in README, the Windows platform is not supported. If you don't have any Linux system, you may try with WSL by installing CLI version of Tizen Studio on it (not recommended).

Regarding the error message, you should run `flutter-tizen` at least once (for initializing of the underlying flutter tool) before debugging the tool on Visual Stduio Code.

**Comment by Bwolfs2** [comment]
Tnks when i install Linux i try again =D
